/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Home extends javax.swing.JFrame {

    String passarNomeHome;
    String passarTipoContaHome;
    String passarSenhaHome;
    int passarNumContaHome;
    boolean passarStatusHome;
    double passarSaldo = 0;
    
    public Home(String nomeHome, String tipoContaHome, String senhaHome, int numContaHome, boolean statusHome, double saldoHome) {
        initComponents();
        
        passarNomeHome = nomeHome;
        passarTipoContaHome = tipoContaHome;
        passarSenhaHome = senhaHome;
        passarNumContaHome = numContaHome;
        passarStatusHome = statusHome;
        passarSaldo = saldoHome;
        
        lblNomeHome.setText("Dono: "+nomeHome);
        lblTipoContaHome.setText("Tipo de Conta: "+tipoContaHome);
        lblSenhaHome.setText("Senha: "+senhaHome);
        lblNumContaHome.setText("Numero da Conta: "+numContaHome);
        
        if(statusHome == true){
            lblStatusHome.setText("Situaçao: Aberta");
        }else{
            lblStatusHome.setText("Situaçao: Fechada");
        }
        
        lblSaldoHome.setText("Saldo: "+saldoHome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNomeHome = new javax.swing.JLabel();
        lblTipoContaHome = new javax.swing.JLabel();
        lblSenhaHome = new javax.swing.JLabel();
        lblNumContaHome = new javax.swing.JLabel();
        lblStatusHome = new javax.swing.JLabel();
        btnOperacoesHome = new javax.swing.JButton();
        lblSaldoHome = new javax.swing.JLabel();
        btnFecharContaHome = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        lblNomeHome.setText("Nome");

        lblTipoContaHome.setText("Tipo de conta");

        lblSenhaHome.setText("senha");

        lblNumContaHome.setText("Numero Conta");

        lblStatusHome.setText("Status");

        btnOperacoesHome.setText("Operacoes");
        btnOperacoesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacoesHomeActionPerformed(evt);
            }
        });

        lblSaldoHome.setText("Saldo");

        btnFecharContaHome.setText("Fechar Conta");
        btnFecharContaHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharContaHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStatusHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumContaHome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblSenhaHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoContaHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomeHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFecharContaHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOperacoesHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNomeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipoContaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenhaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumContaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatusHome)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoHome)
                .addGap(40, 40, 40)
                .addComponent(btnOperacoesHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnFecharContaHome)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperacoesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacoesHomeActionPerformed
        new Operacoes(passarNomeHome, passarTipoContaHome, passarSenhaHome, passarNumContaHome, passarStatusHome, passarSaldo).setVisible(true);
    }//GEN-LAST:event_btnOperacoesHomeActionPerformed

    private void btnFecharContaHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharContaHomeActionPerformed
        
        String varSenhaFecharContaHome = JOptionPane.showInputDialog(rootPane, "Digite a senha:");
        
        if(varSenhaFecharContaHome.equals(passarSenhaHome)){
            if(passarSaldo == 0){
                //System.out.println("If funcionando perfeitamente");
                new TelaPrincipal().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Saque todo o seu dinheiro!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "senha Incorreta!", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFecharContaHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharContaHome;
    private javax.swing.JButton btnOperacoesHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNomeHome;
    private javax.swing.JLabel lblNumContaHome;
    private javax.swing.JLabel lblSaldoHome;
    private javax.swing.JLabel lblSenhaHome;
    private javax.swing.JLabel lblStatusHome;
    private javax.swing.JLabel lblTipoContaHome;
    // End of variables declaration//GEN-END:variables
}
