/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Operacoes extends javax.swing.JFrame {

    boolean saque = false;
    boolean deposito = false;
    
    String nomeCalculoOperacoes;
    String tipoContaCalculoOperacoes;
    String senhaCalculoOperacoes;
    int numContaCalculoOperacoes;
    boolean statusCalculoOperacoes;
    double saldoCalculoOperacoes = 0;
    
    
    public Operacoes(String nomeOperacoes, String tipoContaOperacoes, String senhaOperacoes, int numContaOperacoes, boolean statusOperacoes, double saldoOperacoes) {
        initComponents();
        
        saldoCalculoOperacoes = saldoOperacoes;
        nomeCalculoOperacoes = nomeOperacoes;
        tipoContaCalculoOperacoes = tipoContaOperacoes;
        senhaCalculoOperacoes = senhaOperacoes;
        numContaCalculoOperacoes = numContaOperacoes;
        statusCalculoOperacoes = statusOperacoes;
        
        
        lblSacarOperacoes.setVisible(false);
        lblDepositarOperacoes.setVisible(false);
        txtSacarOperacoes.setVisible(false);
        txtDepositarOperacoes.setVisible(false);
        btnEnviarOperacoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSacarOperacoes = new javax.swing.JLabel();
        txtSacarOperacoes = new javax.swing.JSpinner();
        lblDepositarOperacoes = new javax.swing.JLabel();
        txtDepositarOperacoes = new javax.swing.JSpinner();
        btnEnviarOperacoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOpDepositarOperacoes = new javax.swing.JButton();
        btnOpSacarOperacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operacoes");

        lblSacarOperacoes.setText("Valor a sacar:");

        lblDepositarOperacoes.setText("Valor a depositar:");

        btnEnviarOperacoes.setText("Concluir Operacao");
        btnEnviarOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarOperacoesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Qual operacao deseja realizar?");

        btnOpDepositarOperacoes.setText("Depositar");
        btnOpDepositarOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpDepositarOperacoesActionPerformed(evt);
            }
        });

        btnOpSacarOperacoes.setText("Sacar");
        btnOpSacarOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpSacarOperacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnEnviarOperacoes))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSacarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDepositarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSacarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepositarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnOpDepositarOperacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpSacarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpDepositarOperacoes)
                    .addComponent(btnOpSacarOperacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSacarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSacarOperacoes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepositarOperacoes)
                    .addComponent(txtDepositarOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnEnviarOperacoes)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarOperacoesActionPerformed
        double calculoGeral = 0;
        double varSaque = 0;
        double varDeposito = 0;
        
        String senhaComparar = JOptionPane.showInputDialog(rootPane, "Digite a senha: ");

        if(senhaComparar.equals(senhaCalculoOperacoes)){
            if(deposito == true && saque == false){
                varDeposito = Double.parseDouble(txtDepositarOperacoes.getValue().toString());
                if(varDeposito > 0){
                    calculoGeral = saldoCalculoOperacoes + varDeposito ;
                    saldoCalculoOperacoes = calculoGeral;
                    new Home(nomeCalculoOperacoes, tipoContaCalculoOperacoes, senhaCalculoOperacoes, numContaCalculoOperacoes, statusCalculoOperacoes, saldoCalculoOperacoes).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Valor nao correspndente!", "Inane error", JOptionPane.ERROR_MESSAGE);
            }
            
            }else if(saque == true && deposito == false){
                varSaque = Double.parseDouble(txtSacarOperacoes.getValue().toString());
                if(varSaque > 0 && varSaque <= saldoCalculoOperacoes){
                    calculoGeral = saldoCalculoOperacoes - varSaque;
                    saldoCalculoOperacoes = calculoGeral;
                    new Home(nomeCalculoOperacoes, tipoContaCalculoOperacoes, senhaCalculoOperacoes, numContaCalculoOperacoes, statusCalculoOperacoes, saldoCalculoOperacoes).setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Valor nao correspndente!", "Inane error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Senha errada!", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarOperacoesActionPerformed

    private void btnOpDepositarOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpDepositarOperacoesActionPerformed
        lblDepositarOperacoes.setVisible(true);
        txtDepositarOperacoes.setVisible(true);
        btnEnviarOperacoes.setVisible(true);
        
        txtSacarOperacoes.setVisible(false);
        lblSacarOperacoes.setVisible(false);
        
        deposito = true;
        saque = false;
    }//GEN-LAST:event_btnOpDepositarOperacoesActionPerformed

    private void btnOpSacarOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpSacarOperacoesActionPerformed
        txtSacarOperacoes.setVisible(true);
        lblSacarOperacoes.setVisible(true);
        btnEnviarOperacoes.setVisible(true);
        
        lblDepositarOperacoes.setVisible(false);
        txtDepositarOperacoes.setVisible(false);
        
        saque = true;
        deposito = false;
    }//GEN-LAST:event_btnOpSacarOperacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Operacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarOperacoes;
    private javax.swing.JButton btnOpDepositarOperacoes;
    private javax.swing.JButton btnOpSacarOperacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDepositarOperacoes;
    private javax.swing.JLabel lblSacarOperacoes;
    private javax.swing.JSpinner txtDepositarOperacoes;
    private javax.swing.JSpinner txtSacarOperacoes;
    // End of variables declaration//GEN-END:variables
}
